In [3]:
import tensorflow as tf
import numpy as np
keras = tf.keras

In [5]:
tensor = tf.constant([1,2,3],dtype=tf.float64)
tf.cast(tensor, dtype=tf.int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [39]:
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [53]:
tf.ones(3,dtype=tf.int32) * 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>

In [10]:
tf.zeros((2,5,4),dtype='int32')

<tf.Tensor: shape=(2, 5, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

In [11]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

n을 입력하면 첫항이 1이고 공비가 2인 등비수열을 생성하는 함수를 만드시오 (결과값은 tf.Tensor 데이터, 데이터타입은 tf.int32)\
n = 10일때 (1,2,4,8,16,32,64,128,256,512)

In [43]:
def geometric_sequence(n):
    arr = []
    idx = 1
    num = 1
    for i in range(n):
        arr.append(num)
        num *= idx * 2

    return arr
arr = geometric_sequence(10)
tf.cast(arr, dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)>

In [45]:
def geometric_sequence(n):
    r = tf.range(n,dtype='int32')
    s = tf.ones(n,dtype=tf.int32) * 2
    return s ** r

geometric_sequence(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)>

Rabdom Value(난수)
- 무작위 값을 생성할때 필요함.
- Noise를 재현하거나 test를 한다거나 할 때 많이 사용됨
- 데이터 타입은 상수형태로 반환됨
tf.random에 구현되어 있음.
- tf.random.normal
    - Gaussian Normal Distribution
- tf.random.uniform
    - Uniform Distribution
        - 연속확률분포, 특정범위내 균등하게 나타나 있는 경우.